var seed = 
  [
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ],
    [
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false },
      { "alive": false }
    ]      
  ];

module.exports = seed;
